//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by defaulter-gen. DO NOT EDIT.

package config

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&WorkloadOperator{}, func(obj interface{}) { SetObjectDefaults_WorkloadOperator(obj.(*WorkloadOperator)) })
	return nil
}

func SetObjectDefaults_WorkloadOperator(in *WorkloadOperator) {
	SetDefaults_MetricsServerConfig(&in.MetricsServer)
	SetDefaults_TLSConfig(&in.MetricsServer.TLS)
	SetDefaults_WebhookServerConfig(&in.WebhookServer)
	SetDefaults_TLSConfig(&in.WebhookServer.TLS)
	SetDefaults_DiscoveryConfig(&in.Discovery)
}
